out.txt,字符数：53
out.txt,单词数：7
out.txt,行数：4
out.txt,代码行/空行/注释行：3/0/0
output.txt,字符数：87
output.txt,单词数：8
output.txt,行数：4
output.txt,代码行/空行/注释行：4/0/0
stop.txt,字符数：3
stop.txt,单词数：0
stop.txt,行数：2
stop.txt,代码行/空行/注释行：2/0/0
text.txt,字符数：14
text.txt,单词数：4
text.txt,行数：6
text.txt,代码行/空行/注释行：4/1/1
